### ISSUE TITLE
Add ngx_brotli static module

### ISSUE THREAD

**Issue by eltismerino** [cryptofuture/nginx-hda-bundle#1]
Could you add that module, please? :)

https://github.com/google/ngx_brotli/blob/master/src/ngx_http_brotli_static_module.c

**Comment by cryptofuture** [comment]
Already part of the bundle as a dynamic module. Since 6 Jun.
You can install it with 

```
sudo apt-get install nginx-module-brotli
```

If you using PPA.
And load with:

```
load_module modules/ngx_http_brotli_filter_module.so;
```

libbrotli should install with it automatically.

**Comment by eltismerino** [comment]
I already did that. Still getting:

(edit: sorry for the mess, can't really paste this)

> service nginx restart
> - Restarting nginx nginx                                                                                                                                                                  nginx: [emerg] unknown directive "brotli_static" in /etc/nginx/nginx.conf:53
>   nginx: configuration file /etc/nginx/nginx.conf test failed

dpkg:

```
dpkg -l |grep nginx
ii  nginx                               1.10.1-8-ppa7~trusty                 amd64        high performance web server
ii  nginx-module-brotli                 1.10.1-8-ppa7~trusty                 amd64        Brotli Module
ii  nginx-module-http-headers-more      1.10.1-8-ppa7~trusty                 amd64        http-headers-more module
ii  nginx-module-lenght-hiding-filter   1.10.1-8-ppa7~trusty                 amd64        Lenght Hiding Filter module
```

Seems like you're only incorporating the filter, not the "static" module.

**Comment by cryptofuture** [comment]
Looks like I forgot to add static part indeed. Will look today.

**Comment by cryptofuture** [comment]
ngx_brotli static now available. Try update from PPA again, most likely package will be already published in time you read this message, launchpad little bit slow with big packages like nginx through.
