### ISSUE TITLE
nginx ipv6

### ISSUE THREAD

**Issue by hsie** [cryptofuture/nginx-hda-bundle#10]
thanks for this project and just wonder if you can add ipv6 module at your convenience, thanks in advance!

**Comment by cryptofuture** [comment]
What ipv6 module you talking about? ipv6 support should be in place, `--with-ipv6` flag was removed long time ago.
```
Changes with nginx 1.11.5                                        11 Oct 2016

    *) Change: the --with-ipv6 configure option was removed, now IPv6
       support is configured automatically.
```

**Comment by hsie** [comment]
thanks so much for quick response and I had thought no ipv6 module was enabled as no such output via nginx -V.

Also I just wonder if there is any posibility that you will enable tls 1.3 in the future releases?

**Comment by cryptofuture** [comment]
TLS 1.3 is supported by nginx with `enable-tls1_3` flag, but not supported by openssl, yet. 
Possibly it might be supported in next LTS (18.04), but now its out of meta even in 17.10.
