### ISSUE TITLE
please add nginx-rtmp-module

### ISSUE THREAD

**Issue by wowcut** [cryptofuture/nginx-hda-bundle#11]
Hi, this is a very nice repo and ppa, I like it - thank you very much for your efforts!

It would be great if you would like to add [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module) - that would be a very valuable addition to this ppa!

Thanks and have a nice day!

**Comment by wowcut** [comment]
ok wait [some people](https://docs.peer5.com/guides/setting-up-hls-live-streaming-server-using-nginx/) say that [this fork](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module) "contains more fixes and improvements" - I am not sure. Maybe it would be the best solution to offer both of these as separate modules? 
Edit: after taking a quick look I would prefer the second repo, seems more up2date indeed, but this is not based on some deep analysis...

**Comment by cryptofuture** [comment]
What could you say about [nginx-ts-module](https://github.com/arut/nginx-ts-module)?
[Fork](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module) looks better.
Is rtmpt used with rtmp or could be used without rtmp module?

**Comment by wowcut** [comment]
>What could you say about nginx-ts-module?

Never used that, but if it compiles fine certainly a valuable addition!

> Fork looks better.

Yes, the fork seems to be the one to go with!

> Is rtmpt used with rtmp or could be used without rtmp module?

From what I understand this can be used without the rtmp module.

Thank you very much for your attention!

**Comment by cryptofuture** [comment]
Closed in 27dd1c25c48ba996331f28ce9eb26d04fa7c861f
