### ISSUE TITLE
Nginx brotli update

### ISSUE THREAD

**Issue by btd** [cryptofuture/nginx-hda-bundle#16]
Hi there.

First of all thank you for your awesome work.

May i suggest to switch `ngx_brotli` location from `google/ngx_brotli` which is not supported anymore. To switch to fork from one of libbrotli maintainers https://github.com/eustas/ngx_brotli (also google guy)?

**Comment by cryptofuture** [comment]
Nice. Looks like to the date brotli, I'll try to update bundle along with it and nginx 1.13.8 soon.  I trying to switch/update submodules only if I'm 100% sure I'll be able to build it, this also ensures anyone else could build successfully using the same tag/commit number.

**Comment by btd** [comment]
Awesome thank you.

**Comment by cryptofuture** [comment]
Closed with fbd36660c77b98c155a773b37ff0eb09d90bd9ef

**Comment by cryptofuture** [comment]
@btd  #18 
Did you tested brotli filter module with last update?

**Comment by btd** [comment]
not yet (i noticed launchpad build servers not working for some time)

**Comment by btd** [comment]
I just noticed another issue with it, i will try to test it today also.
