### ISSUE TITLE
Please, add nginx-module-sts and nginx-module-stream-sts

### ISSUE THREAD

**Issue by kryjex** [cryptofuture/nginx-hda-bundle#17]
First of all, thanks for this repo and ppa, you helped me a lot when i've need the installation of nginx-module-vts.

Please, add support for his brother nginx-module-sts, which is vts but for stream module (tcp and udp).

These are theirs repositories:

- https://github.com/vozlt/nginx-module-sts
- https://github.com/vozlt/nginx-module-stream-sts

Thanks!

**Comment by cryptofuture** [comment]
Closed with fbd36660c77b98c155a773b37ff0eb09d90bd9ef
