### ISSUE TITLE
ngx_http_brotli_filter_module broken in 1.13.8-1-ppa7~xenial?

### ISSUE THREAD

**Issue by silverwind** [cryptofuture/nginx-hda-bundle#18]
I just updated to `1.13.8-1-ppa7~xenial` and noticed that broti compression of dynamic content via seems to no longer work, e.g. requests for such resources time out in the browser. The static brotli module seems fine on the other hand.

Relevant config parts:

````nginx
load_module modules/ngx_http_brotli_filter_module.so;
server {
  brotli on;
  brotli_types text/plain text/css application/javascript application/json;
  location / {
    proxy_pass http://127.0.0.1:5000;
  }
}
````

`error.log` shows this error:

````
2018/01/12 11:33:52 [alert] 3458#3458: worker process 3463 exited on signal 9
2018/01/12 11:33:52 [alert] 3458#3458: worker process 3465 exited on signal 9
2018/01/12 11:34:07 [alert] 3472#3472: worker process 3480 exited on signal 9
````

**Comment by cryptofuture** [comment]
This is probably trade for switching to more updated brotli version upstream (#16).
However I don't see any open issues in https://github.com/eustas/ngx_brotli (or even have issues tab disabled)
I'd ping btd too.

**Comment by btd** [comment]
@silverwind @cryptofuture I just tried to update it one one of my servers and did not notice any issues.
My config looks like this:
```
load_module modules/ngx_http_brotli_filter_module.so;
load_module modules/ngx_http_brotli_static_module.so;
....

http {

  brotli on;
...
  brotli_comp_level  6;

...
  brotli_min_length  256;

....
  brotli_types
    application/atom+xml
    application/javascript
    application/json
    application/ld+json
    application/manifest+json
    application/rss+xml
    application/vnd.geo+json
    application/vnd.ms-fontobject
    application/x-font-ttf
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/opentype
    image/bmp
    image/svg+xml
    image/x-icon
    text/cache-manifest
    text/css
    text/plain
    text/vcard
    text/vnd.rim.location.xloc
    text/vtt
    text/x-component
    text/x-cross-domain-policy;

  ....

    server {
....

      location /public/ {
        brotli_static on;
        ...
      }
    }
}
```

(i skipped secitions with upstream and location proxy_pass)

**Comment by btd** [comment]
@silverwind maybe it is some set of settings, do you have exact nginx.conf to reproduce it?

**Comment by silverwind** [comment]
I will attempt to reproduce in a container.

**Comment by btd** [comment]
@silverwind i have a Dockerfile for vanilla nginx + ngx_brotli (i also did not have problem with this and my config)

https://gist.github.com/btd/6aa9f754be228dbac781b5bd79f2a31e

Let me know please if you find anything.

**Comment by silverwind** [comment]
No luck so far with below minimal config. I'll debug the affected machine further.

````nginx
daemon off;
user www-data;
worker_processes auto;
pid /var/run/nginx.pid;
error_log /dev/stdout debug;
load_module modules/ngx_http_brotli_filter_module.so;

events {
  worker_connections 768;
}

http {
  default_type text/plain;

  server {
    listen 5000;
    location / {
      return 200 "something";
    }
  }
  
  server {
    listen 80;
    location / {
      brotli on;
      brotli_types text/plain;
      brotli_min_length 0;
      proxy_pass http://127.0.0.1:5000;
    }
  }
}

**Comment by silverwind** [comment]
I have it narrowed down to the `proxy_buffering off;` statement which triggers the issue, still not reproduced on the container.

**Comment by silverwind** [comment]
Reproduced in the container. Apparently it makes a difference if the upstream is a separate application. Here are the steps:

````console
$ docker run -it -p 127.0.0.1:80:80 ubuntu:16.04
$ cd ~ && apt -y update && apt -y install software-properties-common && apt-add-repository -y ppa:hda-me/nginx-stable && apt -y update && apt -y install nginx nginx-module-brotli python
$ python -m SimpleHTTPServer 8000 &
$ cat > /etc/nginx/nginx.conf
````
Then paste below config hit Return and CTRL-C
````nginx
daemon off;
error_log /dev/stdout debug;
load_module modules/ngx_http_brotli_filter_module.so;

events {
  worker_connections 768;
}

http {
  default_type text/html;

  brotli on;
  brotli_min_length 0;

  server {
    listen 80;
    location / {
      proxy_pass http://127.0.0.1:8000/;
      proxy_buffering off;
    }
  }
}
````
Finally, start the server:
````console
$ nginx
````
Then go to http://localhost, both Chrome and Firefox should hang.

As a workaround, I'll be using `proxy_buffering on;` in the meanwhile. It did work with `off` in previous versions thought.

**Comment by cryptofuture** [comment]
@silverwind What ubuntu releasename do you use in the container?
I can rebuild it in separate ppa with old brotli for the test (rebuilding all ubuntu versions will take a while now, due launchpad still under extra overload)

**Comment by silverwind** [comment]
> What ubuntu releasename do you use in the container?

Not sure what you mean, but my container base is `16.04`. Another PPA to test the old version would be appreciated, I didn't find a way to install the previous version of the original PPA.

**Comment by cryptofuture** [comment]
Try it when it will be ready, thats 1.13.8 with old brotli.
https://launchpad.net/~hda-me/+archive/ubuntu/ngx-tmp

**Comment by btd** [comment]
@silverwind `proxy_buffering off;` has known issues with subrequests. I will try to play with your container and my setup. But actually it makes sense to me, what nginx could pass to gzip/brotli filter if there is no buffer?

**Comment by silverwind** [comment]
@cryptofuture the PPA with old brotli (`1.13.8-2-ppa7~xenial`) works for me with `proxy_buffering off`.

CC @eustas: It looks like something in https://github.com/eustas/ngx_brotli/commit/9891a98811a5d301041298a6507de8acc498e52a broke the brotli filter module when `proxy_buffering off;` is set. see https://github.com/cryptofuture/nginx-hda-bundle/issues/18#issuecomment-357297553 for a repro.

**Comment by eustas** [comment]
Going to investigate it (ASAP) on Monday.

**Comment by eustas** [comment]
It seems, that I've found the problem. Works on simple "Hello" file, hopefully, will work in all cases =)
The root of the problem is that nobody have ever looked at the patch, to catch silly mistakes =(

**Comment by eustas** [comment]
Fix: https://github.com/eustas/ngx_brotli/commit/47550a25d07363f8eb87ef901b2de5883c46352b

**Comment by silverwind** [comment]
Awesome. @cryptofuture would you mind updating your testing ppa to include that fix?

**Comment by cryptofuture** [comment]
Upload done. Check it in 20 minutes or so.
https://launchpad.net/~hda-me/+archive/ubuntu/ngx-tmp/+packages

**Comment by silverwind** [comment]
Thanks, that build looks to be working fine so far with `proxy_buffering off;`!

**Comment by cryptofuture** [comment]
Nice I'll update main ppa and github submodule.
@eustas Huge thanks for fixing it.

**Comment by Kagami** [comment]
I'm using brotli with `proxy_buffering off` too and getting reports from the users that web pages sometimes doesn't get loaded fully (i.e. similar to disconnect in the middle of page load). Though I can't reproduce it by myself.

@silverwind do you experience something similar?

**Comment by silverwind** [comment]
Can't say I heard of such issues. My `error.log` doesn't show any dying worker processes since the last update, check yours.
