### ISSUE TITLE
nginx 1.13.9 released

### ISSUE THREAD

**Issue by karlsoon** [cryptofuture/nginx-hda-bundle#21]
Hello!
Can u please update to latest nginx version? This release include http2 push functionality.

**Comment by cryptofuture** [comment]
Yes I aware about new version. But sadly quit busy, might be be able to do it on the next week. Beside I want to do snap version of the bundle with 1.13.9, which would take extra time.

**Comment by pramathesh** [comment]
Hey, apologies for asking but any ETA on the v1.13.9

**Comment by cryptofuture** [comment]
@pramathesh As fast as we would fix totally not connected by any means to bundle bug on my work, and I do some refactoring for backend. Or as fast as would be a day and I would be in condition to work after 2-3 am  
Sorry for delay.

**Comment by pramathesh** [comment]
I'm sorry for being nosy just do not want such a wonderful project to be abandoned. Like I mentioned in the other thread, I've learnt a lot over our interaction. Looking forward to the next update.

**Comment by pramathesh** [comment]
Hey! Any update?

**Comment by cryptofuture** [comment]
@pramathesh Trying to survive to update. Really sorry, still not able to find spare time after work.

**Comment by pramathesh** [comment]
@cryptofuture No worries take your time. Just do not abandon the project :) we are two releases behind official but as long as the project isn't abandoned it is fine :)

**Comment by pramathesh** [comment]
Hey, @cryptofuture any progress made?

**Comment by cryptofuture** [comment]
@pramathesh I'm afraid not, I'm still can't adapt my timeline for current situation.

**Comment by pramathesh** [comment]
@cryptofuture pray that you don't abandon the project

**Comment by cryptofuture** [comment]
Updated but only xenial and artful, bionic and up needs more module patching.
Had trouble with graphite module, and disabled it. Not closing yet.

**Comment by pramathesh** [comment]
Works like a charm for xenial. Thank you for the efforts and not letting go of this project :)

**Comment by hsie** [comment]
hi, thanks for this and just wonder if when will the latest nginx be upgraded, thanks in advance!

**Comment by Greybane** [comment]
Love the work you're doing, looking forward to the update to 1.15.0 !

**Comment by wowcut** [comment]
just an idea: maybe you should post to nginx mailing list and to other places (Reddit? HN? SOme Ubuntu channel?) that you are searching for collaborators to get this project out of one-person-hobby status? It would be great to see this project grow with more competent backers!

**Comment by cryptofuture** [comment]
Closed in cae5a1f8de07755feb92f17f51c65de04ad4a4c5
@wowcut Maybe you could help with some small promo, but yes I kinda gone from that work, so for now have more time, but might need to make donation thing work for at least a bit.
