### ISSUE TITLE
TLSv1.3 support

### ISSUE THREAD

**Issue by karlsoon** [cryptofuture/nginx-hda-bundle#22]
From docs:
The TLSv1.3 parameter (1.13.0) works only when OpenSSL 1.1.1 built with TLSv1.3 support is used.

From nginx -V
built with OpenSSL 1.0.2g  1 Mar 2016

**Comment by cryptofuture** [comment]
Check https://github.com/cryptofuture/nginx-hda-bundle/issues/6
It might be possible in bionic, but I even hardly doubt it would be in bionic on release time, since they use 1.1.0g

**Comment by karlsoon** [comment]
php ppa have updated openssql - probably u can use this?

**Comment by rofrol** [comment]
In Ubuntu 19.04 there is [openssl](https://packages.ubuntu.com/disco/openssl) 1.1.1b which has support for [TLS 1.3](https://wiki.openssl.org/index.php/TLS1.3).
