### ISSUE TITLE
Load dynamic modules and enable Brotli

### ISSUE THREAD

**Issue by pramathesh** [cryptofuture/nginx-hda-bundle#23]
Hi,

I just googled and reached your git. Trying to learn backend and sysadmin. I wanted to understand if I were to load a dynamic module. I would just go ahead and uncomment the module and it gets activated, right?

Looking forward for 1.13.9  :)

PS: The Brotli compression is enabled automagically right? No need to edit the nginx conf file? I'm a little confused as I'm also seeing gzip set to 'ON' in the conf file. Could you please clarify?

**Comment by cryptofuture** [comment]
> I would just go ahead and uncomment the module and it gets activated, right?

Yes, also you will see instructions after installing submodule

> The Brotli compression is enabled automagically right?

No

**Comment by pramathesh** [comment]
Oh, so I've to install the sub-module and then uncomment the module which needs to be activated? Any guide on how to install a sub-module. Guessing the process will the same for every other module moving on that I need to activate.

Apologies if I come across as naive, I'm trying to learn :)

How do I enable Brotli?

EDIT:

Just figured that it is a simple apt-install process for the submodules and then uncomment and reload nginx to have it functioning. Now where will I get the apt-install 'module-names' from? Also, which modules would you recommend as a must have for WooCommerce/WP Setup?

**Comment by cryptofuture** [comment]
Check packages names at the bottom of the page:

https://launchpad.net/%7Ehda-me/+archive/ubuntu/nginx-stable

**Comment by pramathesh** [comment]
Turns out I only need Brotli and Pagespeed for my usage. Also, I'm facing an error 
'nginx: [emerg] unknown directive "brotli_static" in /etc/nginx/nginx.conf:59'

Could you please help me resolve this, it seems this has been discussed earlier too but it isn't working for me atm.

PS: I know this is a cardinal sin, but any ETA for the latest version which supports http2_push

EDIT: nginx: [emerg] "deny" directive FileCachePath must be set, even for standby in /etc/nginx/nginx.conf:121
Getting this error after setting pagespeed on;

**Comment by cryptofuture** [comment]
```# ngx_brotli filter module - used to compress responses on-the-fly.
load_module modules/ngx_http_brotli_filter_module.so;
# ngx_brotli static module - used to serve pre-compressed files.
# Both ngx_brotli modules could be used separately, but part of nginx-module-brotli package
load_module modules/ngx_http_brotli_static_module.so;
```

**Comment by pramathesh** [comment]
That fixed it! Thank you once again for being so patient and helping me learn along the way. I noticed the link to the project for bortli mentioned on your launchpad page hasn't been updated well over a year. I've found another project that gets updated very frequently and can be found here, are these the same as the ones used in your project or differnt things?

https://github.com/eustas/ngx_brotli

PS: Looking forward to the newest version of NGINX
Also, do you recommend any configuration settings for WordPress for NGINX?

**Comment by cryptofuture** [comment]
Bundle already use https://github.com/eustas/ngx_brotli
Launchpad page might be not updated.
IDK I didn't used WP in years. All software is just static generated pages and node applications for me most of the time.

**Comment by pramathesh** [comment]
Sweet! The launchpad version still directs to ngx_google just typing this out here for anyone who check this in the future. 

Thank You once again :)
