### ISSUE TITLE
disabling TLS v1.0

### ISSUE THREAD

**Issue by pramathesh** [cryptofuture/nginx-hda-bundle#24]
With TLS v1.0 being phased out by the end of the month. I am not quite sure how I would disable that. Tried searching high and low but didn't find any result. The conf file doesn't have any mention of TLS v1.0. Can you advise?

**Comment by cryptofuture** [comment]
you could set protocols directly in the `nginx.conf`
For example:
 `ssl_protocols TLSv1.2 TLSv1.3;`
