### ISSUE TITLE
this nginx version is outdated and dangerous. Got DoS attacked!

### ISSUE THREAD

**Issue by therealmarv** [cryptofuture/nginx-hda-bundle#27]
This nginx version is not up to date.
We got DoS attacked today by this http/2 issue https://news.softpedia.com/news/nginx-security-issues-expose-more-than-14-million-servers-to-dos-attacks-523659.shtml

I really loved your modularity approach but this all means nothing when we can get attacked. Really sad I loose brotli and Google pagespeed for my old sites now :(

Seems the only good way to keep nginx with features is to compile it yourself (I hate this route ... I want to install stuff not custom compile it).

**Comment by cryptofuture** [comment]
I had some issues, but hope it would be updated soon. Unfortunately my last attempts (about 8 month ago) to do updates automatic with script failed, since modules need manual patching too freq.

**Comment by cryptofuture** [comment]
Help with update is welcome: https://github.com/cryptofuture/nginx-hda-bundle/issues/28

**Comment by cryptofuture** [comment]
Closed in cae5a1f8de07755feb92f17f51c65de04ad4a4c5

**Comment by therealmarv** [comment]
amazing @cryptofuture thanks a lot!
