### ISSUE TITLE
GeoIP 2

### ISSUE THREAD

**Issue by Webonaute** [cryptofuture/nginx-hda-bundle#29]
Hi.

Is it possible to add the new GeoIp2 module?

https://github.com/leev/ngx_http_geoip2_module

**Comment by cryptofuture** [comment]
I would check.

**Comment by cryptofuture** [comment]
Closed in c21bcd58b42710b79c3e79088b487d7da9b7bd62

**Comment by cryptofuture** [comment]
@Webonaute 
Package name is `nginx-module-geoip2` 
Let me know how it works for you

**Comment by Webonaute** [comment]
thank. we are looking at it
