### ISSUE TITLE
nginx 1.17.1

### ISSUE THREAD

**Issue by ogunkarakus** [cryptofuture/nginx-hda-bundle#33]
Hi,

nginx released version 1.17.1

When will this repository be updated?

**Comment by cryptofuture** [comment]
> /ping @cryptofuture

Busy. Would upd, when will be able too.

**Comment by ogunkarakus** [comment]
@cryptofuture any progress?

**Comment by cryptofuture** [comment]
No, yet. Too busy with other things, sorry.

**Comment by ogunkarakus** [comment]
@cryptofuture any progress? sorry spamming. 😶

**Comment by cryptofuture** [comment]
I didn't forgot. Have time tomorrow, so proly would be.
