### ISSUE TITLE
How i can build it?

### ISSUE THREAD

**Issue by godjil** [cryptofuture/nginx-hda-bundle#34]
can You help me and explane how i can build it?

**Comment by cryptofuture** [comment]
Basically you download nginx, place debian folder inside and run `dpkg-buildpackage -S -d`
however, the step my slightly different, as you don't have my pgp private key.
You could create new entry in changelog with `dch -i`
Next you could use launchpad or pbuilder, however in the last case you need some extra hooks for additional repos
