### ISSUE TITLE
Update NGINX to 1.17.3

### ISSUE THREAD

**Issue by jamesponddotco** [cryptofuture/nginx-hda-bundle#35]
Hi 👋🏻,

I am just wondering when this update will hit Launchpad, as it was [released today](http://nginx.org/en/CHANGES) and fixes [security issues reported by Netflix](https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-002.md).

Thanks for your awesome work, by the way!

**Comment by cryptofuture** [comment]
Could do Thursday, today is just not realistic for me considering the main work.

**Comment by cryptofuture** [comment]
Close in 6067795eb2237a8493afdf5e100ca03e205f9653
Unfortunately lua-nginx-module is not fully updated, as I was not able to merge graphite branch with last its upstream updates, might fix with next version
