### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by MTecknology** [cryptofuture/nginx-hda-bundle#4]
I stumbled across the related PPA because of a need for the nginx-xmpp patch in a bit of an edge case. It turns out, this package doesn't specify Conflicts: or Replaces: in d/control and causes all sorts of interesting problems.

nginx should conflict with and replace nginx-{light,extras,full,common} and the modules should do the same with their debian/ubuntu counterparts.

**Comment by cryptofuture** [comment]
I never had problems with it on Ubuntu. Usually when nginx from repository installed, thats ends in replacing old nginx, and autoremove deletes the rest. However for at least 6 month I didn't used any nginx versions, beside nginx-hda-bundle
If you have  list of conflicts packages for control file for Ubuntu/Debian, make some pull, and I 'll include it with next nginx version. I kind of busy, so a bit slow to mainline version this time.
Also consider, this bundle was never intended to use on Debian.

**Comment by MTecknology** [comment]
Debian is upstream for Ubuntu and the package split is in newer Ubuntu releases.

The naming scheme for modules is libnginx-mod-<foo>.
Examples:
libnginx-mod-http-auth-pam - PAM authentication module for Nginx
libnginx-mod-http-cache-purge - Purge content from Nginx caches
libnginx-mod-http-dav-ext - WebDAV missing commands support for Nginx
libnginx-mod-http-echo - Bring echo and more shell style goodies to Nginx

As far as seeing these issues crop up in Ubuntu, the report was because of Xenial (16.04).
I could probably make a PR (.... eventually?), but would it be okay if I matched package names as well?

**Comment by cryptofuture** [comment]
In ubuntu 16.04.x i have just nginx-core, nginx-light and nginx-extras (all modules in it) packages. Found libnginx-mod-http-auth-pam in sid only, and seems all libnginx-mod-http-* packages are indeed dynamic modules.
Probably we could include those modules in bundle.

**Comment by cryptofuture** [comment]
Please, try new version and report. Should be fixed in it.

**Comment by MTecknology** [comment]
Looks like a good solution to me. +1
