### ISSUE TITLE
PPA nginx conflicts with nginx-common

### ISSUE THREAD

**Issue by mikemaccana** [cryptofuture/nginx-hda-bundle#5]
Upgrading a 16.04 system with nginx already installed:

     Unpacking nginx (1.11.12-1-ppa7~xenial) over (1.10.0-0ubuntu0.16.04.4) ...
dpkg: error processing archive /var/cache/apt/archives/nginx_1.11.12-1-ppa7~xenial_amd64.deb (--unpack):
      trying to overwrite '/etc/logrotate.d/nginx', which is also in package nginx-common 1.10.0-0ubuntu0.16.04.4
     dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)

Obviously the issue can be fixed by uninstalling the existing nginx packages first, but if the PPA provided an upgraded nginx-common users could upgrade without warnings.

**Comment by cryptofuture** [comment]
Currently we have:
```
Replaces: nginx-core, nginx-extras, nginx-full, nginx-light
```
I could add nginx-common also. I think I just forgot about it, after all +8 dynamic modules with last update and more compatibility with zesty libnginx-mod-* naming.

**Comment by cryptofuture** [comment]
Please try new build from PPA and report. Will be published in approximately 30 minutes.
