### ISSUE TITLE
Certificate Transparency

### ISSUE THREAD

**Issue by kravietz** [cryptofuture/nginx-hda-bundle#7]
There's this Nginx module implementing TLS Certificate Transparency which is going to become more and more demanded as Chrome will enforce CT by end of this year:

https://github.com/grahamedgecombe/nginx-ct

**Comment by cryptofuture** [comment]
I'll look into it after business trip. If it worth it, I'll add it with
next nginx mainline release.
However, judging by module readme file, it needs newer openssl version
(newer then in xenial), and this means I can't include it in ppa. 
.

**Comment by cryptofuture** [comment]
I really like it and will include it in the bundle. But it will be not workable even in artful. It includes same 1.0.2g version like in xenial and zesty right now. And I'm [strongly against](https://github.com/cryptofuture/nginx-hda-bundle/issues/6) openssl maintaining. However, I think people who need it capable to take risk and to rebuild with higher openssl version.   
Things and openssl version could change in artful, thats why I think its still worth to include it in the bundle.
