### ISSUE TITLE
Server header is different between HTTP 1 and HTTP 2

### ISSUE THREAD

**Issue by silverwind** [cryptofuture/nginx-hda-bundle#9]
This seems unintentional:

````console
$ curl --http1.1 -I https://host | grep Server
Server: cloudflare-nginx
$ curl --http2 -I https://host | grep Server
server: nginx
````

**Comment by cryptofuture** [comment]
This is bad, I plan to update bundle tomorrow, and surely will look into it. I consider it critical enough, this is surely not what I wanted. Nice catch!

**Comment by cryptofuture** [comment]
Might be a solution, anyway need a proper test.
https://medium.com/@zhnebula/nginx-change-http2-header-b5ad0f63a840

**Comment by cryptofuture** [comment]
Close in 7f3002f425205d230c894a1c8200a42596d7d8a7
